### ISSUE TITLE
Error while running the script, "failed to establish a new connection"

### ISSUE THREAD

**Issue by Ghavio1516** [aahashemi/YouTubeAutomation-Reddit#10]
I got this error while running the script, although i didnt input any AWS keys because my AWS account is still on hold for verification. ( i will try again after my AWS account is verified)

Starting ..........

Logged in to Reddit successfully!
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/pi/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/pi/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/pi/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/pi/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/pi/.local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/pi/.local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7faa81ccd0>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/pi/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/pi/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faa81ccd0>: Failed to establish a new connection: [Errno 113] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/prawcore/requestor.py", line 58, in request
    return self._http.request(
  File "/home/pi/.local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faa81ccd0>: Failed to establish a new connection: [Errno 113] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/YouTubeAutomation-Reddit/main.py", line 110, in <module>
    main()
  File "/home/pi/YouTubeAutomation-Reddit/main.py", line 19, in main
    thread = reddit.get_thread(reddit=my_reddit,
  File "/home/pi/YouTubeAutomation-Reddit/Reddit/reddit.py", line 36, in get_thread
    sorted_threads = sorted(threads, key=lambda x: int(x.score), reverse=True)
  File "/home/pi/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 63, in __next__
    self._next_batch()
  File "/home/pi/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/pi/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/praw/reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/home/pi/.local/lib/python3.9/site-packages/praw/reddit.py", line 739, in _objectify_request
    self.request(
  File "/home/pi/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/praw/reddit.py", line 941, in request
    return self._core.request(
  File "/home/pi/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 330, in request
    return self._request_with_retries(
  File "/home/pi/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 253, in _request_with_retries
    return self._do_retry(
  File "/home/pi/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "/home/pi/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 253, in _request_with_retries
    return self._do_retry(
  File "/home/pi/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "/home/pi/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/home/pi/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "/home/pi/.local/lib/python3.9/site-packages/prawcore/rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "/home/pi/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "/home/pi/.local/lib/python3.9/site-packages/prawcore/auth.py", line 373, in refresh
    self._request_token(
  File "/home/pi/.local/lib/python3.9/site-packages/prawcore/auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "/home/pi/.local/lib/python3.9/site-packages/prawcore/auth.py", line 30, in _post
    response = self._requestor.request(
  File "/home/pi/.local/lib/python3.9/site-packages/prawcore/requestor.py", line 62, in request
    raise RequestException(exc, args, kwargs)
prawcore.exceptions.RequestException: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faa81ccd0>: Failed to establish a new connection: [Errno 113] No route to host'))

**Comment by realsbd** [comment]
I have the same issue, I guess reddit have make changes to there website

**Comment by lilhiggy** [comment]
Has anyone found a way to fix this?

**Comment by kanito80** [comment]
[It was working fine until February 8, 2024 when it started giving me this error and I can't find a solution! Does anyone know how to solve it?](https://github.com/aahashemi/YouTubeAutomation-Reddit/issues/12#issuecomment-1761751944)

**Comment by nssharmaofficial** [comment]
@realsbd @kanito80 @lilhiggy @Ghavio1516 I fixed the issue. Check working solution [here](https://github.com/nssharmaofficial/reddit-hole) since this does not seem to be active.
