### ISSUE TITLE
Fix for waiting for locator("id=loginUsername")

### ISSUE THREAD

**Issue by giuseppe99barchetta** [aahashemi/YouTubeAutomation-Reddit#23]
Hi, I post my trace for the error:

Logged in to Reddit successfully!
Chosen thread: What instantly ages someone? -- Score: 13375
10 comments are chosen
Launching Headless Browser...
Traceback (most recent call last):
  File "/home/giuseppe/YouTubeAutomation-Reddit/main.py", line 112, in <module>
    main()
  File "/home/giuseppe/YouTubeAutomation-Reddit/main.py", line 35, in main
    get_screenshots_of_reddit_posts(reddit_thread=thread, reddit_comments=comments, screenshot_num=1)
  File "/home/giuseppe/YouTubeAutomation-Reddit/Graphics/screenshot.py", line 62, in get_screenshots_of_reddit_posts
    page.locator("id=loginUsername").fill(my_config["RedditCredential"]["username"])
  File "/usr/local/lib/python3.11/dist-packages/playwright/sync_api/_generated.py", line 15305, in fill
    self._sync(
  File "/usr/local/lib/python3.11/dist-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/playwright/_impl/_locator.py", line 198, in fill
    return await self._frame.fill(self._selector, strict=True, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/playwright/_impl/_frame.py", line 528, in fill
    await self._channel.send("fill", locals_to_params(locals()))
  File "/usr/local/lib/python3.11/dist-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("id=loginUsername")
============================================================

**Comment by siril-teja** [comment]
I ran into this a while ago. Rebooting the system solved it for me.

**Comment by alexvsc5** [comment]
@giuseppe99barchetta did you solve the issue? I got the exact same one, but reboot does not solve it for me...
